.\" dnf-langpacks - Plugin for dnf
.TH "DNF.PLUGIN.LANGPACKS" "8" "August 13, 2015" "0.15.0" "dnf-langpacks"
.SH "NAME"
dnf.langpacks.plugin \- DNF langpacks plugin 
.SH "SYNOPSIS"
\fBdnf\fP [command] [package ...]
.SH "DESCRIPTION"
.PP 
\fBdnf-langpacks\fP is a plugin for dnf to install language packs. This plugin
provides various commands.
.PP 
\fIcommands\fP available are:
.br 
.I \fB * langavailable  [language1] [language2] [\&.\&.\&.]
   This command allows user to find if language support is available for the given input languages.

.br
.I \fB * langinfo  [language1] [language2] [\&.\&.\&.]
   This command will show the user what packages will get installed by a given input languages.

.br
.I \fB * langlist
   This command will show the user what languages are already installed(enabled) on the system.

.br
.I \fB * langinstall  [language1] [language2] [\&.\&.\&.]
   This command will install the given input languages.

.br
.I \fB * langremove  [language1] [language2] [\&.\&.\&.]
   This command will remove the given input languages.

.br
This plugin also provide option to enable additional languages. Just add locale
code to langpacks_locale config item in /etc/dnf/plugins/langpacks.conf

.SH "EXAMPLES"
.PP
   \fBTo check if langpacks are available for language codes de, hi and language names Japanese and Portuguese (Brazil).\fP
   dnf langavailable de "Japanese" hi "Portuguese (Brazil)"

.PP
   \fBTo check what packages will get installed for language codes de, hi and language names Japanese and Portuguese (Brazil).\fP
   dnf langinfo de "Japanese" hi "Portuguese (Brazil)"

.PP
   \fBTo check what languages are already installed on your system.\fP
   dnf langlist

.PP
   \fBTo install the languages for language codes de, hi and language names Japanese and Portuguese (Brazil).\fP
   dnf langinstall de "Japanese" hi "Portuguese (Brazil)"

.PP
   \fBTo remove the languages for language codes de, hi and language names Japanese and Portuguese (Brazil).\fP
   dnf langremove de "Japanese" hi "Portuguese (Brazil)"

.SH "NOTES"
   These commands accept language codes or language names or mix of them as a input.
   General usage for end users is like this:
   1) Use langavailable command to see if required language support is available.
   2) Use langinfo command to know what packages will get installed.
   3) Use langlist to know if you have required language already installed or not.
   4) Use langinstall to install any new available language.
   5) Or Use langremove to remove any installed language.

.PP
.SH AUTHOR
Parag Nemade
.PP
.SH "SEE ALSO"
.nf
.I dnf (8)
.fi

.PP
.SH "BUGS"
Please report any bugs in Red Hat bugzilla, https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora
.fi
